// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiJTfS421OL_rK0xTEr4h6D_grwI03T3M',
    appId: '1:947807049845:android:f1e807ccae3ee5235b803c',
    messagingSenderId: '947807049845',
    projectId: 'fluttershare-515c2',
    databaseURL: 'https://fluttershare-515c2.firebaseio.com',
    storageBucket: 'fluttershare-515c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYxkNDsK13pfzkapmMw0jL_qPD8v0Sq_g',
    appId: '1:947807049845:ios:8be970416f60593e5b803c',
    messagingSenderId: '947807049845',
    projectId: 'fluttershare-515c2',
    databaseURL: 'https://fluttershare-515c2.firebaseio.com',
    storageBucket: 'fluttershare-515c2.appspot.com',
    androidClientId: '947807049845-0ahfl5ijkt2se62u1mse7ne603oa9opf.apps.googleusercontent.com',
    iosClientId: '947807049845-fsdu4rnbbdll0pish1jcpn6auupqn43a.apps.googleusercontent.com',
    iosBundleId: 'com.gaurav.fluttershare',
  );
}
